server:
  servlet:
    context-path: /cangchu
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SUN?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
###### MyBatis config ######
mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mapping/*.xml
    #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.lishijiee.pojo
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
